apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuromorphic-edge-processor
  labels:
    app: neuromorphic-edge-processor
    version: v3.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neuromorphic-edge-processor
  template:
    metadata:
      labels:
        app: neuromorphic-edge-processor
        version: v3.0.0
    spec:
      containers:
      - name: neuromorphic-processor
        image: neuromorphic-edge-processor:3.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: neuromorphic-service
spec:
  selector:
    app: neuromorphic-edge-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
